Repository Icinga/icinga-vagrant, pull requests merged in 2018-09, with the labels that each got.

#162 Modify base box to generic bento/centos-7
  distributed/Vagrantfile.nodes
  elastic/Vagrantfile.nodes
  env/Vagrantfile.nodes
  graylog/Vagrantfile.nodes
  influxdb/Vagrantfile.nodes
  standalone/Vagrantfile.nodes
Labels: parallels, provider, virtualbox

#163 Improve Vagrant includes for nodes and local
  distributed/Vagrantfile
  elastic/Vagrantfile
  env/Vagrantfile
  graylog/Vagrantfile
  influxdb/Vagrantfile
  standalone/Vagrantfile
  tools/vagrant_helper.rb
Labels: enhancement

#164 Icinga 2: Add namespace config demo from 2.10
  .puppet/modules/profiles/manifests/icinga/icinga2.pp
  .puppet/modules/profiles/templates/icinga/icinga2/config/demo/namespaces.conf.erb
Labels: enhancement, icinga2
