Repository Icinga/icinga-vagrant, pull requests merged in 2019-11, with the labels that each got.

#192 Elastic Stack 7
  .puppet/hieradata/common.yaml
  .puppet/modules/profiles/manifests/elastic/icingabeat.pp
  doc/screenshot/vagrant_elastic_kibana_icingabeat.png
Labels: area/elastic, enhancement

#190 Support vagrant-hostmanager
  README.md
  centos7-dev/Vagrantfile
  distributed/Vagrantfile
  elastic/Vagrantfile
  graylog/Vagrantfile
  influxdb/Vagrantfile
  standalone/Vagrantfile
  tools/vagrant_helper.rb
Labels: area/provisioner, enhancement

#197 Update integrations: Grafana 4.6.4, Director 1.7.2, Dashing 3.0.0
  .puppet/hieradata/common.yaml
  doc/screenshot/vagrant_dashing_icinga2.png
Labels: enhancement

#198 Update to Graylog 3
  .puppet/hieradata/common.yaml
  .puppet/modules/mongodb/lib/puppet/provider/mongodb_replset/mongo.rb
  .puppet/modules/mongodb/manifests/db.pp
  .puppet/modules/mongodb/manifests/opsmanager/config.pp
  .puppet/modules/profiles/manifests/base/system.pp
  .puppet/modules/profiles/manifests/graylog/elasticsearch.pp
  .puppet/modules/profiles/manifests/graylog/mongodb.pp
  .puppet/modules/profiles/manifests/graylog/plugin.pp
  .puppet/modules/profiles/manifests/graylog/server.pp
  .puppet/modules/profiles/manifests/icinga/icinga2.pp
  .puppet/modules/profiles/templates/graylog/check-graylog2-stream-wrapper.erb
  .puppet/modules/profiles/templates/graylog/graylog-seed.py.erb
  .puppet/modules/profiles/templates/graylog/graylog-seed.rb.erb
  .puppet/modules/profiles/templates/graylog/icinga-vagrant-dashboard-content-pack-9031558d-2431-4d30-af33-44ab0bc5f109-1.json.erb
  .puppet/modules/profiles/templates/icinga/icinga2/config/demo/commands.conf.erb
  .puppet/modules/profiles/templates/icinga/icinga2/config/demo/hosts.conf.erb
  .puppet/modules/profiles/templates/icinga/icinga2/config/demo/notifications.conf.erb
  .puppet/modules/profiles/templates/icinga/icinga2/config/demo/services.conf.erb
  README.md
  doc/screenshot/vagrant_graylog_icinga.png
  graylog/environments/vagrant/manifests/default.pp
Labels: area/graylog, enhancement

#199 Update Grafana to 6.5.0
  .puppet/hieradata/common.yaml
Labels: area/grafana
